apiVersion: v1
kind: Pod
metadata:
  name: pod-command
  namespace: default
  labels:
    app: pod
spec:
  containers:
  - name: mynginx
    image: docker.io/library/nginx:1.23.1
  - name: mybusybox
    image: docker.io/library/busybox:1.35.0
    command: ["/bin/sh","-c","touch /tmp/hello.txt;while true;do /bin/echo $(date +%T) >> /tmp/hello.txt; sleep 3; done;"]
