apiVersion: v1
kind: Pod
metadata:
  name: pod-imagepull
  namespace: default
spec:
  containers:
  - name: mynginx
    image: docker.io/library/nginx:1.23.1
    imagePullPolicy: Always                                     # 设置镜像拉取策略
  - name: mybusybox
    image: docker.io/library/busybox:1.35.0
