apiVersion: v1
kind: Pod
metadata:
  name: pod-initcontainer
  namespace: default
spec:
  containers:
  - name: main-container
    image: docker.io/library/nginx:1.23.1
    ports: 
    - name: nginx-port
      containerPort: 80
  initContainers:
  - name: test-mysql
    image: docker.io/library/busybox:1.35.0
    command: ['sh', '-c', 'until ping 192.16.1.100 -c 1 ; do echo waiting for mysql...; sleep 2; done;']
  - name: test-redis
    image: docker.io/library/busybox:1.35.0
    command: ['sh', '-c', 'until ping 192.16.1.200 -c 1 ; do echo waiting for reids...; sleep 2; done;']
