apiVersion: v1
kind: Pod
metadata:
  name: pod-ports
  namespace: default
spec:
  containers:
  - name: mynginx
    image:  docker.io/library/nginx:1.23.1
    ports: # 设置容器暴露的端口列表
    - name: nginx-port
      containerPort: 80
      protocol: TCP
