apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod1
  namespace: default
spec:
  containers:
  - name: busybox
    image: docker.io/library/busybox:1.35.0
    command: ["/bin/sh","-c","while true;do echo pod1 >> /root/out.txt; sleep 10; done;"]
    volumeMounts:
    - name: volume
      mountPath: /root/
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc1
        readOnly: false
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod2
  namespace: default
spec:
  containers:
  - name: busybox
    image: docker.io/library/busybox:1.35.0
    command: ["/bin/sh","-c","while true;do echo pod2 >> /root/out.txt; sleep 10; done;"]
    volumeMounts:
    - name: volume
      mountPath: /root/
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc2
        readOnly: false  
